<?= $this->doctype() ?>
<? $MatchedRouteName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getMatchedRouteName(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('njuko - Test technique')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/njuko-test-technique.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body style="background:url('<?= $this->basePath('img/background.jpeg') ?>') no-repeat fixed center top !important;">
        <nav class="navbar navbar-inverse navbar-fixed-top navbar-njuko" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/logo_njuko.png') ?>" height="28" alt="Njuko Logo"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li <? if($MatchedRouteName == "home"){ echo 'class="active"'; } ?>><a href="<?= $this->url('home') ?>">Accueil</a></li>
                        <li <? if($MatchedRouteName == "participant/list"){ echo 'class="active"'; } ?>><a href="<?= $this->url('participant/list') ?>">Liste des participants</a></li>
                        <li <? if($MatchedRouteName == "classement"){ echo 'class="active"'; } ?>><a href="<?= $this->url('classement') ?>">Classements</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container main-container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
