<div class="row">
    <div class="col-md-12 text-center">
        <h1>Test technique</h1>
    </div>
</div>
<div class="row mt-20">
    <div class="col-md-6">
        <p>
            <b>Contexte</b><br/>
            <br/>
            Vous êtes organisateur d'un événement sportif !<br/>
            Vous organisez une course de 12km avec un dénivelé positif de 1km dans le Pays Basque, et un semi-marathon le lendemain.<br/>
            <br/>
            Les inscriptions à votre événement sont clôturées et l'événement va commencer !
            Avant de commencer la course, vous allez devoir générer des numéros de dossard pour chaque participant. (de 1 à 100)<br/>
            La course commence !<br/>
            A chaque passage d'un participant sur la ligne d'arrivée, le chronométreur présent sur la course, vous remet le temps de passage du coureur.

        </p>
    </div>
    <div class="col-md-6">
        <div class="alert alert-info" role="alert">

            <p>
                <b>Techonologies utilisées</b><br/>
                <br/>
                Zend Framework 3+<br/>
                Doctrine<br/>
                <br/>
                Jquery 3+<br/>
                Twitter Bootstrap 3+<br/>
                <br/>
                <b>Données pour vous aider :</b><br/>
                <a href="./datas.sql">- Datas pour remplir les tables</a><br/>

            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <p>
            <b>What you need to do !</b><br/>
            <br/>
            Permettre à l'organisateur de changer l'événement auquel participe un inscrit.<br/>
            <br/>
            Permettre la suppression d'un participant qui ne se présente pas à la course.<br/>
            <br/>
            Dans la liste des participants, vous avez un bouton "Générer les numéros de dossards".<br/>
            Ce bouton doit permettre une attribution automatique de n° de dossard à chaque participant dans un ordre chronologique. (de 1 à 100)<br/>
            <br/>
            Vous allez également devoir permettre à l'organisateur de saisir le temps de passage (sur la ligne d'arrivée) de chaque participant. (Modifier un participant)<br/>
            <br/>
            Dernières étapes, vous allez devoir créer un classement général, un classement homme, et un classement femme, dans un nouveau menu "Classement"<br/>
            Ce classement devra afficher le dossard, le nom, le prénom, et le temps qu'a mis le participant à effectuer sa course !
        </p>
    </div>
</div>